name: Build and Push to Azure Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and tag Docker image (with ENV secret as build arg)
      run: |
        docker build \
          -f src/Dockerfile \
          --build-arg ENV_CONTENT="${{ secrets.ENV }}" \
          -t ${{ secrets.ACR_LOGIN_SERVER }}/techworkshop-l300-ai-apps-and-agents:${{ github.sha }} \
          src

    - name: Push image to Azure Container Registry
      run: |
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/techworkshop-l300-ai-apps-and-agents:${{ github.sha }}